apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "api-con-auth2.fullname" . }}
  labels:
    {{- include "api-con-auth2.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "api-con-auth2.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-con-auth2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-con-auth2.selectorLabels" . | nindent 8 }}
    spec:
      containers: 
        - name: {{ include "api-con-auth2.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretName }}
                  key: POSTGRES_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-con-auth2.fullname" . }}-service
  labels:
    {{- include "api-con-auth2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "api-con-auth2.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
