apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-con-auth2.fullname" . }}-headless
  labels:
    {{- include "api-con-auth2.labels" . | nindent 4 }}
spec:
  clusterIP: None  
  selector:
    {{- include "api-con-auth2.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
