apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
    POSTGRES_HOST: cG9zdGdyZXMtc2VydmljZQ==
    POSTGRES_DB: YXBw
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: cG9zdGdyZXM=
